#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5 6 7 8 9 []=

bspc config border_width         0
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#173448" #d4af37
bspc config normal_border_color "#173448"
bspc config active_border_color "#292D3E"
bspc config presel_feedback_color "292D3E"

xsetroot -cursor_name left_ptr
xinput set-prop "12" "libinput Accel Profile Enabled" 0 1 0
setxkbmap -layout 'us,ru' -option 'grp:alt_shift_toggle'

# redshift -l 59.9386:30.3141 &
picom &

feh --bg-fill $HOME/Documents/mountain-sky-scenery-digital-art-4k-wallpaper-uhdpaper.com-773@0@i.jpg

killall -q polybar
$HOME/.config/polybar/launch.sh &
