#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 =[]

bspc config border_width         0 #2
bspc config window_gap           0 #12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color  "#173448" #"#d4af37"
bspc config active_border_color   "#292D3E"
bspc config normal_border_color   "#173448"
bspc config presel_feedback_color "292D3E"

xset s off
xset -dpms
xset r rate 200 40
setxkbmap -layout 'us,ru' -option 'grp:alt_shift_toggle'
# setxkbmap -layout 'us,ru' -option 'grp:shifts_toggle'
xsetroot -cursor_name left_ptr
xinput set-prop "9" "libinput Accel Profile Enabled" 0 1 0

# redshift -l 59.9386:30.3141 &
picom &

feh --bg-fill $HOME/Documents/mountain-sky-scenery-digital-art-4k-wallpaper-uhdpaper.com-773@0@i.jpg

killall -q polybar
$HOME/.config/polybar/launch.sh &
