# Collection of colorschemes for easy configuration
# https://github.com/alacritty/alacritty-theme

general.import = [
  "~/.config/alacritty/themes/one_dark.toml"
]

[window]
decorations = "None"
# opacity = 0.8
# padding.x = 20
# padding.y = 20

[font]
normal.family = "JetBrainsMono Nerd Font Mono"
# normal.family = "FiraCode Nerd Font"
# normal.family = "Iosevka"
# normal.family = "Operator Mono Lig"
size = 17.0

# normal = { family = "SauceCodePro Nerd Font Mono", style = "Medium" }
# bold = { family = "SauceCodePro Nerd Font Mono", style = "Semibold" }
# italic = { family = "SauceCodePro Nerd Font Mono", style = "Italic" }
# size = 22.0

[colors]
draw_bold_text_with_bright_colors = true

[[keyboard.bindings]]
key = "C"
mods = "Alt"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Alt"
action = "Paste"
