# Collection of colorschemes for easy configuration
# https://github.com/alacritty/alacritty-theme

general.import = [
  "~/.config/alacritty/themes/one_dark.toml"
]

[window]
# opacity = 0.8
# padding.x = 20
# padding.y = 20

[font]
normal.family = "JetBrainsMono Nerd Font Mono"
# normal.family = "FiraCode Nerd Font"
# normal.family = "Iosevka"
# normal.family = "Operator Mono Lig"
size = 17.0
