# Collection of colorschemes for easy configuration
# https://github.com/alacritty/alacritty-theme

# import = [
#   "~/.config/alacritty/themes/Cobalt2.toml"
# ]

[window]
opacity = 0.8
# padding.x = 20
# padding.y = 20

[font]
normal.family = "FiraCode Nerd Font" # "JetBrainsMono Nerd Font Mono" # "Operator Mono Lig"
size = 20.0

[colors.primary]
background = "0x173448"
foreground = "0xffffff"

# [colors.normal]
# black  = "0x181a20"
# red    = "0xf6465d"
# green  = "0x0ecb81"
# yellow = "0xfcd535"
# blue   = "0x0088ff"
# magets = "0xaa759f"
# cyan   = "0x7ffcff"
# white  = "0xeaecef"
